### PR TITLE
Upgraded main aspnet core project to 2.0

### PR DESCRIPTION
**Pull request by maxstoll94**
Upgraded the Mvc.JQuery.DataTables.AspNetCore and Mvc.JQuery.DataTables.AspNetCore.Example with their dependencies to asp.net core 2.0, also fixed the issues that arose through this upgrade.

### CODE REVIEW

**Comment by mcintyre321** [comment]
[Failed build](https://ci.appveyor.com/project/mcintyre321/mvc-jquery-datatables/build/1.5.38), it might be due to this: https://stackoverflow.com/questions/45569378/upgrading-to-net-core-2-0-packagetargetfallback-and-assettargetfallback-cannot

**Comment by maxstoll94** [comment]
My apologies for the late reply and thank you for your advice. I should have fixed all the build errors now.

**Comment by mcintyre321** [comment]
Are all those js/css assets not required for the example project?

**Comment by mcintyre321** [comment]
Great work BTW.

**Pull request merged**
